# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyq < Formula
  desc "Unified jq-syntax query tool for JSON, YAML, and TOML"
  homepage "https://github.com/troll-warlord/anyq"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/troll-warlord/anyq/releases/download/v0.2.1/anyq_0.2.1_darwin_amd64.tar.gz"
      sha256 "ddf76e53a747f28f0d882ef06244dea1da478b429a0987538fe0fa2d9bca248b"

      define_method(:install) do
        bin.install "anyq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/troll-warlord/anyq/releases/download/v0.2.1/anyq_0.2.1_darwin_arm64.tar.gz"
      sha256 "751035802a5e86657bf6a0fafc2a69f154ca7963e959ccc37c04d4265b4a8064"

      define_method(:install) do
        bin.install "anyq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/troll-warlord/anyq/releases/download/v0.2.1/anyq_0.2.1_linux_amd64.tar.gz"
      sha256 "f38e4d519d05cd56a6b94ffb0efc9c1de5542742f4855bcb8afe6b88606f6aa9"
      define_method(:install) do
        bin.install "anyq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/troll-warlord/anyq/releases/download/v0.2.1/anyq_0.2.1_linux_arm64.tar.gz"
      sha256 "f9758fba257fdd7e2ba024a4505b4d9451902005312e44bfc276e74d6ef76bce"
      define_method(:install) do
        bin.install "anyq"
      end
    end
  end

  test do
    system "#{bin}/anyq", "--version"
  end
end
