# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyq < Formula
  desc "Unified jq-syntax query tool for JSON, YAML, and TOML"
  homepage "https://github.com/troll-warlord/anyq"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/troll-warlord/anyq/releases/download/v0.0.1/anyq_0.0.1_darwin_amd64.tar.gz"
      sha256 "f38dd66c219f4cc43178d281236db2034f8846ca8d7451ad7131c608ae04654f"

      define_method(:install) do
        bin.install "anyq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/troll-warlord/anyq/releases/download/v0.0.1/anyq_0.0.1_darwin_arm64.tar.gz"
      sha256 "bbd96f496c176c10ca0aef1b15afd68d01188b1b66b01f70442458e2c520d4da"

      define_method(:install) do
        bin.install "anyq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/troll-warlord/anyq/releases/download/v0.0.1/anyq_0.0.1_linux_amd64.tar.gz"
      sha256 "3e44c6f2cba3a8a4701e8fac5d4d50ccac55a6629705eb8933460eec9a9fc594"
      define_method(:install) do
        bin.install "anyq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/troll-warlord/anyq/releases/download/v0.0.1/anyq_0.0.1_linux_arm64.tar.gz"
      sha256 "2d6f4ae66afd7a81d24ed031ed76d2fb6cf7a82dc5bec7418f4fd3d1ccb5648e"
      define_method(:install) do
        bin.install "anyq"
      end
    end
  end

  test do
    system "#{bin}/anyq", "--version"
  end
end
